import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "KICKORY",
//   description: "Generated by #MHS",
// };
import { App_NAME, APP_SLOGAN } from "@/lib/constants";
export const metadata: Metadata = {
  title:{template: `%s | ${App_NAME}`, default: App_NAME},
  keywords: ["kickory", "kickory.com", "#MHS", "shoes", "sneakers"],
  authors: [{ name: "#MHS" }],
  creator: "#MHS",
  publisher: "#MHS",
  description: APP_SLOGAN,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
